import * as THREE from 'three';
import { KTX2Loader } from 'three/addons/loaders/KTX2Loader.js';

// Loads the KTX2 (Basis Universal) PBR texture sets generated by tools/gen-textures.mjs.
// Each material has `<name>_ar.ktx2` (albedo RGB + roughness A, sRGB) and `<name>_n.ktx2`
// (tangent-space normal). Textures stay GPU-compressed (BC7/ASTC/ETC2… picked per device).
// The terrain's ground layers are packed into CompressedArrayTextures so one shader samples
// all of them with two samplers.
const BASE = '/assets/textures/';
export const TERRAIN_LAYERS = ['grass', 'dirt', 'sand', 'rock', 'snow', 'pavement'];

export class TextureLib {
  constructor(renderer) {
    this.renderer = renderer;
    this.loader = new KTX2Loader().setTranscoderPath('/basis/').detectSupport(renderer);
    this.cache = new Map();
    this.maxAniso = renderer.capabilities.getMaxAnisotropy();
  }

  async load(name, { srgb = true, repeat = true } = {}) {
    if (this.cache.has(name)) return this.cache.get(name);
    const p = this.loader.loadAsync(BASE + name + '.ktx2').then((t) => {
      t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
      if (repeat) t.wrapS = t.wrapT = THREE.RepeatWrapping;
      t.anisotropy = Math.min(8, this.maxAniso);
      return t;
    });
    this.cache.set(name, p);
    return p;
  }

  /** {ar, n} pair for one material. */
  async material(name) {
    const [ar, n] = await Promise.all([this.load(name + '_ar'), this.load(name + '_n', { srgb: false })]);
    return { ar, n };
  }

  /** Pack same-size, same-format KTX2 textures into one array texture (all mip levels). */
  static toArray(textures, srgb) {
    const t0 = textures[0];
    const levels = Math.min(...textures.map((t) => t.mipmaps.length));
    const mipmaps = [];
    for (let l = 0; l < levels; l++) {
      const parts = textures.map((t) => t.mipmaps[l].data);
      const size = parts.reduce((s, p) => s + p.byteLength, 0);
      const data = new parts[0].constructor(size / parts[0].BYTES_PER_ELEMENT);
      let off = 0;
      for (const p of parts) { data.set(p, off); off += p.length; }
      mipmaps.push({ data, width: t0.mipmaps[l].width, height: t0.mipmaps[l].height });
    }
    const arr = new THREE.CompressedArrayTexture(mipmaps, t0.image.width, t0.image.height, textures.length, t0.format, t0.type);
    arr.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    arr.wrapS = arr.wrapT = THREE.RepeatWrapping;
    arr.minFilter = levels > 1 ? THREE.LinearMipmapLinearFilter : THREE.LinearFilter;
    arr.magFilter = THREE.LinearFilter;
    arr.generateMipmaps = false;
    arr.needsUpdate = true;
    return arr;
  }

  async terrainArrays() {
    const sets = await Promise.all(TERRAIN_LAYERS.map((n) => this.material(n)));
    const ar = TextureLib.toArray(sets.map((s) => s.ar), true);
    const n = TextureLib.toArray(sets.map((s) => s.n), false);
    ar.anisotropy = n.anisotropy = Math.min(8, this.maxAniso);
    return { ar, n };
  }
}
